### ISSUE TITLE
Features Request.. [Push Notification]

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#1]
Can You Add a Notification..
. For the Airing Episode..
Like The Notification inside the App... 
But Can You make like Notification for the Phone System...

🔔🔔

**Comment by zend10** [comment]
Yes, push notification is in the plan. I'm not very certain how it should be implemented yet, but I've been thinking about it.

https://zend10.github.io/AL-chan/plan.html

**Comment by Secuential** [comment]
Came here to suggest the same thing. It's good to see it in the high priority list!

**Comment by zend10** [comment]
In case you miss it:
https://twitter.com/alchan_app/status/1318400299627806721?s=20

**Comment by zend10** [comment]
Implemented in v.1.1.9.
