### ISSUE TITLE
Edge to edge support

### ISSUE THREAD

**Issue by axiel7** [zend10/AL-chan#10]
Hi,
You should consider adding edge to edge support to your app on Android 10+ devices, the app will look better specially with system gestures enabled.

If I have time I'll try to open a pull request.
Thanks!

**Comment by zend10** [comment]
I'm actually not aware how it looks differently on edge to edge screen on Android 10+ devices, mind showing me the screenshot?

**Comment by axiel7** [comment]
@zend10 Sure, here's an example:
![edge-to-edge_ex](https://miro.medium.com/max/675/1*JvQG9PD7qvD3zhHq-gpc_w.gif)
Source: https://medium.com/androiddevelopers/gesture-navigation-going-edge-to-edge-812f62e4e83e

And this is how is looking on your app (the navigation bar is black and not transparent):
![Screenshot_20200801-094852](https://user-images.githubusercontent.com/12379835/89097120-62ad1e80-d3dc-11ea-9fa5-45794f571d6b.png)

**Comment by zend10** [comment]
I see. I didn't notice that.

**Comment by zend10** [comment]
Implemented in v.1.2.0.
