### ISSUE TITLE
Hide empty tag headings when using filter's search

### ISSUE THREAD

**Issue by BaccanoMob** [zend10/AL-chan#102]
When using filter, selecting tags using search is slighting difficult (with the keyboard on, the screen gets more cramped in phone)
![WhatsApp Image 2022-10-18 at 7 26 46 PM](https://user-images.githubusercontent.com/82655889/196451228-47760192-175f-40b7-95f1-7dbe24c7374b.jpeg)
For example, searching "Harem"
Actual outcome:
![WhatsApp Image 2022-10-18 at 7 26 45 PM](https://user-images.githubusercontent.com/82655889/196451242-4d0dfaf3-038a-4ac5-abcf-76502e127f7c.jpeg)
Preferred outcome:
![WhatsApp Image 2022-10-18 at 7 36 07 PM](https://user-images.githubusercontent.com/82655889/196458181-29e906be-2397-4222-a344-854ba59232f4.jpeg)
Hiding the empty tag heading would make the screen less cramped as shown above and quicker to choose from (esp for users with smaller screen).

**Comment by zend10** [comment]
Implemented in 2.1.0.
