### ISSUE TITLE
Rate limiting issue.

### ISSUE THREAD

**Issue by Mr-Cracker-Pro** [zend10/AL-chan#104]
Please fix the rate limit issue. When I open the app, it shows the rate limit and the contents are not loaded properly.

**Comment by onkoe** [comment]
Cracker,
I think this is due to AniList having their site more locked down. There isn’t an official response yet, but #93 may be of help. You might take a look and see if this sounds familiar!

**Comment by zend10** [comment]
Duplicate with https://github.com/zend10/AL-chan/issues/93

I hope it's better now with the Beta. Out of Beta very, very soon.
