### ISSUE TITLE
New early access version fails to launch

### ISSUE THREAD

**Issue by Vlixz** [zend10/AL-chan#105]
The app keeps crashing when opening, most of the time the following error is shown ("Failed to load from cache").

**Comment by imashnake0** [comment]
AniList's servers are down currently, pretty sure that's why it crashes. I'll post an update here once they're up again :)

**Comment by Vlixz** [comment]
Did not realize that, my apologies, hopefully that's the issue.

**Comment by zend10** [comment]
Found what's the issue with it now.
