### ISSUE TITLE
Optional option to change release time format

### ISSUE THREAD

**Issue by JafarAbbas33** [zend10/AL-chan#109]
Currently in the `Anime List`, the format of showing next episode timing is: `TV . Ep. xx in x days. You are x episodes behind.` For me who wants to quickly glance over when is the next one releasing is a bit problematic. I have to focus alot between all those numbers. This is the current format:
![photo_2023-01-25_13-30-56](https://user-images.githubusercontent.com/68061936/214510785-d4d1c56e-3a7e-4da7-8f10-e7785d0fb149.jpg)
What my recommendation is something similar to what `AniLib` does. Which shows the following format:
![photo_2023-01-25_13-31-00](https://user-images.githubusercontent.com/68061936/214511112-75b1a9b7-1917-4ac9-bcd4-c6faf7efd158.jpg)
I edited a snapshot with your theme in mind so you can easily understand what I mean:
![raw0](https://user-images.githubusercontent.com/68061936/214520597-b05c61df-8d1e-4416-9abe-f14ce2c5a8f0.png)
As you can see, it is so clear with just a glance which is the next episode and at what time. Atleast for me, your app will be unrivaled if you introduced this format ;). And also at the bottom right corner instead of `+1 EP`, if you just show `+` sign, it will save space and make the UI cleaner and elegant. Attaching an example:
![raw1](https://user-images.githubusercontent.com/68061936/214524535-9beda2d3-c8f0-42bd-a3d1-8704eb4b2cbe.png)
Thanks a ton for this amazing app!

**Comment by zend10** [comment]
This is very subjective. If there are more similar request, I might consider it but for now it's rarely asked for.
