### ISSUE TITLE
Apply score system setting globally

### ISSUE THREAD

**Issue by axiel7** [zend10/AL-chan#11]
Hi,
Currently you can choose various score system settings to your list, but this settings only applies to your personal list. It would be great to extend the chosen format to the rest of the app (Ex: when viewing an Anime info)

Thanks!

**Comment by zend10** [comment]
I don't think that's possible, we can only use 0-100 system globally. The only other place where other scoring system can be applied to is for our own stats. Correct me if I'm wrong.

**Comment by axiel7** [comment]
I don't know how the AniList API works, but you could convert the 0-100 score to 0-10 or 0.0-10.0, or I'm wrong?
I'm not sure about the other scoring system though.

**Comment by zend10** [comment]
I see what you mean. The API returns 0-100 and I don't think converting them by myself is a good idea. There's almost no point in doing so. 

Say if you use 0-10 system, you'll see plenty of 8/10 and you have no idea which one is higher. Even worse if you're using smiley or star, you'll see plenty of :) and have no idea if it's 70 or 80.

I think it's only applicable for our own stats, not globally.

**Comment by zend10** [comment]
Seems like I'll never do this anymore.
