### ISSUE TITLE
No device push notifications

### ISSUE THREAD

**Issue by emmaexe** [zend10/AL-chan#110]
I am not receiving push notifications. I am moving away from an old app that hasn't received updates in years to anilist+an android app.  I still have the old app installed and it pushes notifications instantly when  a new episode releases but alchan does not. I am receiving notifications in app but not on the device. I tested this twice. First time I ignored the notification from the old app but the alchan notification never arrived. The second time I opened alchan when I got the notification in the old app and saw the notification in the in-app notification menu but the device push notification was never sent.

I am on MIUI Global v13.0.4 Stable using Al-chan v1.9.2 installed via google play store. All notifications are enabled and battery saver is set to no restrictions on the app (meaning it can run in the background infinitely).

**Comment by KelvinCrag** [comment]
I'm facing the same problem. Which version gives notification?

**Comment by KelvinCrag** [comment]
![20230722_130020-COLLAGE](https://github.com/zend10/AL-chan/assets/64832927/ee6aed06-8394-4656-b420-19813d01c9ac)

@zend10 it still doesn't work :'(

**Comment by zend10** [comment]
Yeah, I messed up. I'll not reopen this thread. Can continue in this thread instead https://github.com/zend10/AL-chan/issues/112.
