### ISSUE TITLE
Adding i18n support.

### ISSUE THREAD

**Issue by xkww3n** [zend10/AL-chan#111]
I'd like to translate this app into Simplified Chinese as some Chinese also use AniList and this app. Would you please consider adding i18n support?

**Comment by zend10** [comment]
I need more people convince me if supporting more languages would be helpful for them. 

All of AniList's information is in English, which will not be possible to localize. So, at best, only the menu would be localized. All those important Anime description will still be in English. Will it even worth it?

**Comment by zend10** [comment]
Closing this thread. Can continue discussion in https://github.com/zend10/AL-chan/issues/69
