### ISSUE TITLE
Permissions disappeared

### ISSUE THREAD

**Issue by AnthonSan** [zend10/AL-chan#112]
Hello i am sorry to bother you, but i have a problem,i guess it's from my phone (miui 14 poco x3 pro) well here it is,when i update to the new version 1.9.3 the permissions and notification access disappears, what can i do?
![Screenshot_2023-04-06-13-46-38-976_com miui securitycenter](https://user-images.githubusercontent.com/115561266/230355973-2092999f-5362-4320-9361-e2552363afbe.jpg)
![Screenshot_2023-04-06-13-46-43-965_com google android permissioncontroller](https://user-images.githubusercontent.com/115561266/230355977-b07e783f-b566-44e0-8540-b6735622d5fd.jpg)
![Screenshot_2023-04-06-13-47-09-646_com android settings](https://user-images.githubusercontent.com/115561266/230355980-e3ed6ecf-b7de-46ba-8b97-fb8b5e93a291.jpg)
![Screenshot_2023-04-06-13-47-12-289_com google android permissioncontroller](https://user-images.githubusercontent.com/115561266/230355982-51dcc6eb-1650-43c1-8632-a2fac4daf879.jpg)

**Comment by zend10** [comment]
I just noticed this is not Android 13 device. Notification permission should be enabled by default, unless it has been disabled manually. If you still think it's a bug on app side, can reopen the thread.

**Comment by zend10** [comment]
I googled this device and it somehow says only upgradeable to Android 12. Alright, if it's Android 13, I need to prompt Notification Permission manually which I haven't implemented.

**Comment by AnthonSan** [comment]
Thank you so much for your time and amazing work on this app.. Best of luck

**Comment by zend10** [comment]
Get the v2.0.0. It should work fine now.

**Comment by AnthonSan** [comment]
Hello,i hope you doing well,sadly the notification problem is still there even after i reinstalled the app

**Comment by zend10** [comment]
Seems like it. The permission dialog only shows up after Notification Channel is created. On first install, it hasn't been created. Will fix it.

**Comment by alsoGAMER** [comment]
2.0.0 on Android 13, app didn't request any permission nor exposes any notification channel, so I can't manually grant them

**Comment by zend10** [comment]
Yes, I've found the issue. It's mainly because of the missing permission in Manifest. Fixed it in version/2.0.1. Will publish it next week.

**Comment by zend10** [comment]
Surely this time it's fixed in 2.0.1.

**Comment by AnthonSan** [comment]
Thank you for your hard work!
