### ISSUE TITLE
Not set date end when change status

### ISSUE THREAD

**Issue by JhonnySalles** [zend10/AL-chan#115]
When opening the registry edition and changing the status to completed, the app does not record the end date, not even if it saves after the change status. You need it is necessary to set the date manually. (the site only puts the end date when saved).

Version: google play

![Screenshot_20230702_205336_AL-chan](https://github.com/zend10/AL-chan/assets/43912638/6dca1768-da03-4a39-b9b8-361f0e5b3e89)

**Comment by zend10** [comment]
Will be fixed on next update.
