### ISSUE TITLE
"failed to load from cache"

### ISSUE THREAD

**Issue by JoNuttanon1994** [zend10/AL-chan#119]
Hello, I have just updated to version 2.0, it has a symptom that says "failed to load from cache" which may negatively affect the list through the anime that I have done. So what should admin do to make it convenient to use immediately? or until the release of a new version as soon as possible and the most stable, would it be good? Would you please help speed up fixing these fake problems?
![Screenshot_2023 07 25_09 30 51 340](https://github.com/zend10/AL-chan/assets/52192172/5bd4c731-0d44-415a-80a1-912f68c58b59)

**Comment by zend10** [comment]
Do you have lots of anime in your list?

**Comment by JoNuttanon1994** [comment]
> Do you have lots of anime in your list?

On the anilist website where my list is kept, it actually exists.

**Comment by zend10** [comment]
Can you give me your AniList username?

**Comment by JoNuttanon1994** [comment]
> Can you give me your AniList username?

The username I use is JoNatthanon1994.

**Comment by zend10** [comment]
Yeah, 6.7k entries. The app would throw a timeout even before managed to load the entire thing. Talked about it in this thread already https://github.com/zend10/AL-chan/issues/114, even 4k entries is bad enough for the app. I'll probably handle it some time but it's definitely quite low in the priority at this moment.
