### ISSUE TITLE
Android 13+ Themed Icon

### ISSUE THREAD

**Issue by infanf** [zend10/AL-chan#124]
Hi @zend10 
I'd like to add a themed icon for the app and replace the bitmap icon with a vector version in the process. Here are two Screenshots from my local test build:

![](https://i.imgur.com/mhz2HxX.png)
![](https://i.imgur.com/V37N0Y5.png)

**Comment by zend10** [comment]
Go for it. Please target your Pull Request to `version/2.1.0`.

**Comment by infanf** [comment]
Thanks for the quick response, pull request is #100

**Comment by zend10** [comment]
Added in 2.1.0.
