### ISSUE TITLE
Bug report: instant crash when viewing a post with large image

### ISSUE THREAD

**Issue by Evil-Dragon** [zend10/AL-chan#128]
Using V2.0.1 on Android 13 on Samsung S23 Ultra.

Been having an issue where AL-Chan will instantly crash and close when viewing this post or any comments/replies: https://anilist.co/activity/605798697

I think it's because the attached image is a large file size or dimensions and AL-Chan doesn't know how to handle it? Image size on imgur is 6120x8160 pixels.

**Comment by zend10** [comment]
Thanks for the report. Yes, it is indeed because of the huge image.

**Comment by zend10** [comment]
Fixed in 2.1.0.
