### ISSUE TITLE
Feature Request [Sort Next Airing & Filter Exclude Genre]

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#13]
**1. NOTIFICATION LOCATION**
It is Ok If You change The Notification Location...(It is To Small) 
Instead Create Another Tab for The Notification Location...

**2. PLANNING NOTIFICATION**
When The Planning Anime Is Aired.. Is there posibility that    it will Notify Us That The Anime Is Aired or Released

**3. Better FILTER**
The Sort "Next Airing"
Is there A Posibility that It Will prioritized the Ongoing Anime...( I Mean That The Ongoing anime Is at the Top)
Because Right now The Sort "Next Airing" Is That The Finished Anime Is In the Top...

**4. +Ep Button**
The +Ep Button Will disapear if youre At The Latest Episode...

I mean That If You Are Ep 7 And The Latest Episode Of the Anime Is At 7... The +EP Button Will disappear....
And Cannot be Added Until the Next Episode is Aired...

**Comment by ImPudding-tech** [comment]
And One More Thing..

Ability to Edit This Tab.. ![Screenshot_20200825_222005_com.zen.alchan.jpg](https://user-images.githubusercontent.com/65703094/91186069-2a6dd700-e721-11ea-9498-e1b3baf48bf0.jpg)

And I think It Is Easier.. To Edit.. Data

**Comment by zend10** [comment]
Not this one. I don't think it's needed to add another way to edit entry.

**Comment by ImPudding-tech** [comment]
Also Theres A Bug In List Setting...

In Anime List Setting... It Only Shows Two

![Screenshot_20200826_095347_com.zen.alchan.jpg](https://user-images.githubusercontent.com/65703094/91246440-671dea80-e782-11ea-9ace-ec1a607cd99e.jpg)


..

**Comment by zend10** [comment]
I'm actually aware of that but I can't really do much as it's actually on AniList's end. You can click on that "Reset to Default" to _fix_ it.

**Comment by ImPudding-tech** [comment]
Zend10... Does the App have The  Filter That Unchecked Genre....

Example..
✔️		FANTASY
❌		Horror...

FOR EXAMPLE I LIKE ANIME THAT HAVE FANTASY GENRE BUT I DONT LIKE Horror... ....

**Comment by zend10** [comment]
Yes, there are improvement to be made to the filter. This genre is one of them.

**Comment by ImPudding-tech** [comment]
And A Little Favor....

Can You Make The Episode Number **BOLD**

LIKE this...
Ep **6** on Sat..

If It ia Ok...

**Comment by ImPudding-tech** [comment]
Zend10... ONE more thing....

Can You Add Coundown Timer... NOT ONLY THE DAY IT WILL RELEASE...

BECAUSE IT IS HARD TO NOTICE... THE DATE... (Its Small) 

![Screenshot_20200904_230848.jpg](https://user-images.githubusercontent.com/65703094/92254535-9f9c9180-ef03-11ea-9918-4cf8653d8c71.jpg)

RATHER THAN Add Like Anichart.. Countdown..

![Screenshot_20200904_231351.jpg](https://user-images.githubusercontent.com/65703094/92255016-5436b300-ef04-11ea-990b-d1e0e6293be3.jpg)

AND IT IS VERY USEFULL..

**Comment by zend10** [comment]
Implemented partially on v.1.1.3.

Better filter will be implemented next time.

**Comment by ImPudding-tech** [comment]
-  Also add X Button inside or outside the Search Pannel (so it is easier to erase) 

- The Bug In List Setting Still there. I think it is because I have Alot of Custom Anime List ( I Click "reset to default" nothings Happen) 

Btw... I love the Latest Release... ❤️❤️

**Comment by zend10** [comment]
Better filter is implemented on v.1.1.5.
