### ISSUE TITLE
Search bar to prompt category selection

### ISSUE THREAD

**Issue by BaccanoMob** [zend10/AL-chan#130]
The search bar "What are you looking for?" right now defaults to anime, it would great if it opens a drawer to choose between anime, manga, characters, staff, studios first (similar to explore). Or have a default selection option in the setting.

I apparently search a lot for mangas so its abit annoying, I tihnk it was tabbed previously so it was single click so it didnt feel stuffed before.

**Comment by zend10** [comment]
Yeah I'm planning to do more than this, but I guess this can be a quick fix for now.

**Comment by zend10** [comment]
Added in 2.1.0.
