### ISSUE TITLE
Bug report: Failed to fetch the latest data. Anime list is loaded from cache.

### ISSUE THREAD

**Issue by JoNatthanon** [zend10/AL-chan#131]
I use a mobile phone Tecno Spark 8C (Android 11). When closing and opening the app a second time, it pops up an error saying "Failed to fetch the latest data. Anime list is loaded from cache." When I closed the task and reopened the app, it kept saying "failed to load from cache" and over the past few days it was crashing again and again. How do you fix this problem? I'm in a very bad mood. 
![alchanV2fix](https://github.com/zend10/AL-chan/assets/142714590/ef4332b3-5922-4ea3-9f5a-593d9aa681fb)
![alchanV2fix2](https://github.com/zend10/AL-chan/assets/142714590/51fcffd2-6865-4a87-8a85-f2dcf1c925a2)

**Comment by zend10** [comment]
App has issues with lists with several thousands of entries. It's not going to be pretty but I'm planning to make the app handle list differently for massive list.

**Comment by JoNatthanon** [comment]
> App has issues with lists with several thousands of entries. It's not going to be pretty but I'm planning to make the app handle list differently for massive list.

thank you so much.

**Comment by JoNatthanon** [comment]
Admin, when will the latest version 2.1.0 be released to fix these problems?

**Comment by zend10** [comment]
I'll be releasing this soon, but if you want to try it early and see if it's fixed for you, you can grab it here:
https://play.google.com/apps/test/RQdSTF1EW-g/ahAO29uNRKe1ktMTWAWXvaN2WHdX1g3sLVcR0WeLsKv-4UD0AORxMBenMTZUFk8TDvqOhuWS8MUds5jF_TtSNjcztq

You will need to switch on your Play Store developer option first to install this:
https://www.androidauthority.com/google-play-developer-options-975226/

**Comment by JoNatthanon** [comment]
> I'll be releasing this soon, but if you want to try it early and see if it's fixed for you, you can grab it here:
> https://play.google.com/apps/test/RQdSTF1EW-g/ahAO29uNRKe1ktMTWAWXvaN2WHdX1g3sLVcR0WeLsKv-4UD0AORxMBenMTZUFk8TDvqOhuWS8MUds5jF_TtSNjcztq
> 
> You will need to switch on your Play Store developer option first to install this:
> https://www.androidauthority.com/google-play-developer-options-975226/

Finally, the app was miraculously successful during this time.  thank you very much

**Comment by zend10** [comment]
Fixed in 2.1.0.

However, the catch is Tag filter and Releasing Today are no longer available for users with more than 1500 entries. It is necessary because it's increasing the loading time and payload size significantly.

While it's not exactly the same, you can still do Tag filter in Explore screen and tick "Only show series on my list". As for Releasing Today, can make use of Calendar.
