### ISSUE TITLE
List Grid View go to Anime button issue

### ISSUE THREAD

**Issue by EnArvy** [zend10/AL-chan#135]
In grid view, each show has a card, clicking on which edits the entry. This is fine. There is also a floating button with the show name. Earlier, clicking on this button led to the details page of the show. However z this button is now bugged. It leads to the show only when clicked on the empty space on the button, and not when clicking in the text itself.

In attached pic, the purple region doesn't work, whereas pink works as intended.![Screenshot_2023-09-10-01-22-14-949-edit_com.zen.alchan.jpg](https://github.com/zend10/AL-chan/assets/70991883/4d6414df-46dd-4b1f-ac43-0743b1981929)

**Comment by zend10** [comment]
Thank you for the report.

**Comment by zend10** [comment]
Fixed in 2.1.0.
