### ISSUE TITLE
Error when trying to sort anime by title in  seasonal chart

### ISSUE THREAD

**Issue by SilverKnight-Z** [zend10/AL-chan#137]
Al-chan gives me an error when I try to sort anime by title in the seasonal chart. I can sort by other criteria without problem 

Al-chan version: 2.0.0 - 2.0.1
OS: One UI 3.1 - Android 11

![Screenshot_20230925-125436_AL-chan.jpg](https://github.com/zend10/AL-chan/assets/82909608/fdc09f92-825a-4409-9662-adad3b2a49e0)

**Comment by zend10** [comment]
Thanks for the report. Fixed in 2.1.0.
