### ISSUE TITLE
Enhancements & Features Suggestions [Set status default to Planning & Better navigation in list]

### ISSUE THREAD

**Issue by ElFrostburnMC** [zend10/AL-chan#14]
Here are some suggestions for Al-Chan which I think that might be useful and improve the app:

1. When a new Anime is added to a list using the search tab, set the new default status to be added to "Planning" instead of "Watching" (in my case this would save some time when adding a new Anime) 
2. When searching for an Anime, add the current status (in case it's already on a list) on the preview
3. The ability to jump between different types of lists (Watching, Planning...) without having to press the button (1st attachment) and then select which one do you want to access, this could be done by adding a new "tab/section" with the different lists in the top of the UI 
4. An ability to schedule a change of Theme at the Morning/Evening, like Android 10 Auto Dark Theme
![IMG_20200828_205012](https://user-images.githubusercontent.com/65023891/91605122-40bda200-e970-11ea-9a34-0f0972ce2b25.jpg)

**Comment by zend10** [comment]
1. I think it makes more sense to have it default to Planning. Alright.

2. Alright.

3. Not this one. I'll stick to navigating each list one by one. It's more workload for not so much benefit. Instead, I've been considering moving the button from the Toolbar to the bottom by using Floating Action Button.

4. I'm not sure about this. I don't think many people actually even use the Light Mode as it is. At least each time people sending me a screenshot, it is always the Dark Mode.

**Comment by zend10** [comment]
Implemented on v.1.1.3.
