### ISSUE TITLE
AL-Chan not working after Android 14 update

### ISSUE THREAD

**Issue by sdMickey** [zend10/AL-chan#141]
Yesterday I updated my Pixel 7 to Android 14 and from yesterday evening, the AL-Chan app refuses to load or refresh and bring new content. The only content I can see has been loaded from.
After booting up the app it says "something went wrong try again". After refreshing it says "failed to fetch the latest data, anime list is loaded from cache"

![Screenshot_20231016-075507.png](https://github.com/zend10/AL-chan/assets/54260201/74f3d1f9-91b1-42d9-b5c9-62c2b2764d54)

![Screenshot_20231016-075612.png](https://github.com/zend10/AL-chan/assets/54260201/4152b51d-024d-4111-a8e1-f2ccf422734a)

Is this an issue of Android 14 or is the api not responding currently?

**Comment by sdMickey** [comment]
One new observation I made:

I tried 4 apps for Android from the app list available on anilist site. It seems like none of them are working right now. But there is no news of anilist being down or anything.

**Comment by BaccanoMob** [comment]
Apparently, its a cloudflare issue not an OS issue. If you open anilist in browser you'll see the check to verify human thing. As far as I know al-chan app cant fix something like this so you will have to wait till cloudflare cools down. Temporary fix is to use a vpn.

**Comment by sdMickey** [comment]
> Apparently, its a cloudflare issue not an OS issue. If you open anilist in browser you'll see the check to verify human thing. As far as I know al-chan app cant fix something like this so you will have to wait till cloudflare cools down. Temporary fix is to use a vpn.

You were right. Worked after connecting to a vpn. Although I'm fine with this temporary fix. Do we have any idea how to overcome that cloudflare issue. Is there a quota i exceeded? Can I do something to speed up the process of waiting for it to cool down?

**Comment by zend10** [comment]
> Apparently, its a cloudflare issue not an OS issue. If you open anilist in browser you'll see the check to verify human thing. As far as I know al-chan app cant fix something like this so you will have to wait till cloudflare cools down. Temporary fix is to use a vpn.

Thanks for the finding. Seems like there's been hiccup for few days already.



> You were right. Worked after connecting to a vpn. Although I'm fine with this temporary fix. Do we have any idea how to overcome that cloudflare issue. Is there a quota i exceeded? Can I do something to speed up the process of waiting for it to cool down?

There's nothing we can do. I believe this is automated and temporary only while AniList is facing heavy load, possibly from certain region, and that's why VPN works.
