### ISSUE TITLE
Enable autocorrect in "note" fields

### ISSUE THREAD

**Issue by Eragonnogare** [zend10/AL-chan#155]
Currently when editing/adding a note to a series the text field does not trigger autocorrect or autocomplete to be enabled on your keyboard. This is very frustrating, and should probably be an easy fix (I imagine it's just a tag on that specific field or something).
![image](https://github.com/zend10/AL-chan/assets/43831501/d649ccd6-cfc8-4cf6-8cf6-274fdea55b9e)

**Comment by zend10** [comment]
What keyboard are you using there? Autocomplete is not disabled there. For example, it's still showing fine with Gboard.

**Comment by Eragonnogare** [comment]
I'm using SwiftKey keyboard. My friend on the built in Android keyboard on her phone has the same issue - no autocomplete, no autocorrect.

**Comment by Eragonnogare** [comment]
(whoops, misclicked. Not completed.)

**Comment by zend10** [comment]
Thanks for the report. Good to know SwiftKey kinda ignore some keyboard handling.

**Comment by Eragonnogare** [comment]
🤷‍♂️I just hope you can fix it soon lol. I wonder if it's just some keyboards specifically handling things _better_, since the default Samsung one seems to have the same issue and all that.

**Comment by zend10** [comment]
Fixed in https://github.com/zend10/AL-chan/releases/tag/v2.1.2
