### ISSUE TITLE
Getting the error "Couldn't find apikey.properties" error while building the project

### ISSUE THREAD

**Issue by CrazyDiamond4444** [zend10/AL-chan#158]
Hello. I am a fairly new android developer who started learning Android Studio and Kotlin two weeks ago, and I have been using your app for more than a few months. So I wanted to inspect your code for learning how to use query and mutation provided by Anilist, so I downloaded the zip file of your project, and after I unzip the file and put it in my projects folder I tried to build the project but when I did I got this problem

>Build file 'C:\Users\(my username)\AndroidStudioProjects\AL-chan-master\app\build.gradle' line: 18

>A problem occurred evaluating project ':app'.
> C:\Users\Yusuf\AndroidStudioProjects\AL-chan-master\apikey.properties (system cannot find the specified file)

I would be grateful if you could help

**Comment by zend10** [comment]
Hello. In the root folder, create a file and name it `apikey.properties`. In that file, add:
```
YOUTUBE_API_KEY=""
SPOTIFY_API_KEY=""
```
You'll not be able to find the anime song from YouTube and Spotify, but the rest of the app will work fine.

**Comment by CrazyDiamond4444** [comment]
Thank you for your response. After I have done what you told me, when ı try to run the project I get this error

>Execution failed for task ':app:validateSigningDebug'.
> Keystore file 'C:\Users\(my username)\AndroidStudioProjects\AL-chan-master\keystore\debug.keystore' not found for signing config 'debug'.

I would be thankful if you can help me with this too

**Comment by zend10** [comment]
In build.gradle in app folder, remove:
```
signingConfigs {
    debug {
        storeFile file(KEYSTORE_PATH_DEV)
        storePassword KEYSTORE_PASSWORD_DEV
        keyAlias KEY_ALIAS_DEV
        keyPassword KEY_PASSWORD_DEV
    }
}
```
and
```
signingConfig signingConfigs.debug
```

**Comment by CrazyDiamond4444** [comment]
Thank you that worked
