### ISSUE TITLE
[List Order Suggestion] - Organize every "List's Filter Sort by" in Alphabetical Order as Anilist's Website does

### ISSUE THREAD

**Issue by ElFrostburnMC** [zend10/AL-chan#17]
[Organize every "List's Filter Sort by" in Alphabetical Order as Anilist's Website does]:

This could help to find entries on "Planning" Lists (which, as someone is planning to watch them, is awkward to add a score without watching/reading the Anime/Manga) without having to touch the settings of "Completed" Lists. 

Anilist 's Website already does it, it displays the "Completed" Animes/Mangas (or any other list with an Anime or Manga with a score) from Highest to Lowest Score (and by alphabetical order if it's the case) and the rest of List's are Displayed by alphabetical order (from A-Z), Here is an example:
![IMG_20200908_012603](https://user-images.githubusercontent.com/65023891/92420368-3c189b00-f173-11ea-8216-2330509d2ffa.jpg)

And also as I said, if there is a list with entries with scores, organize the entries with the same scores by alphabetical order (A-Z), here is an example as how they should be: (the numbers show the position in which they should be placed from top [1] to bottom [4]
![IMG_20200908_012501](https://user-images.githubusercontent.com/65023891/92420377-49ce2080-f173-11ea-859c-4c8048c98b55.jpg)

But this suggestion also applies to all Filters (see the attachment below), if there's more than one entry with the same "parameters" in order to be shown on that position, make them to be ordered from A-Z
![IMG_20200908_010922](https://user-images.githubusercontent.com/65023891/92420447-9a457e00-f173-11ea-8ca5-5aef0718b418.jpg)

I know this explanation may be a bit weird and confusing (Indeed, this suggestion is to set the order of the Anime and Manga entries as the Anilist's Website on Al-chan) and I may repeat some points over and over again, if you don't understand something, please feel free to ask :)

**Comment by zend10** [comment]
Yes, I see. Basically to order them in alphabetical order if the score between each entry is even.

**Comment by zend10** [comment]
Fixed on v.1.1.3.
