### ISSUE TITLE
BUGS/REQUEST (I Think) 

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#18]
- If I search the  Anime/Manga with the Other Titles in  Explore It will show the Anime/Manga But If I search In My Anime/Manga List It Wont Show And It Wont Search The Synonyms Of the Anime/Manga It Only Search The PREFERED Title..

![Screenshot_20200909_184829_com.zen.alchan.jpg](https://user-images.githubusercontent.com/65703094/92590607-17393a80-f2cf-11ea-9fc3-e2f8a23b5730.jpg)
![Screenshot_20200909_184437_com.zen.alchan.jpg](https://user-images.githubusercontent.com/65703094/92590613-199b9480-f2cf-11ea-9bc5-cdea0c445cfe.jpg)

- And In Overview... In Anilist Home.. I WAS Thinking if I should Tell you This but... I Thinks It is Already Planned.. OR not Necessary
![Screenshot_20200909_185754_com.android.chrome.jpg](https://user-images.githubusercontent.com/65703094/92591099-daba0e80-f2cf-11ea-9f8d-0ebf12fbd179.jpg)
![Screenshot_20200909_185725_com.zen.alchan.jpg](https://user-images.githubusercontent.com/65703094/92591105-ddb4ff00-f2cf-11ea-8822-672aff7b3e0d.jpg)
   

- Put All Sort Order in Default List Order (I Think It is Planned)

**Comment by zend10** [comment]
1. Yeah it's not handled, I should have checked all the names. Chizuru is super cute by the way.

2. This embed is sadly not possible to implement as far as I know, or at least I have no idea how to handle it. Unlike AniList website, I can't possibly get the series image and info from the URL alone. I have to make a request to AniList API to get those info. Even then not only it's complicated to handle, it's also not a very good idea as we'll have to keep sending lots and lots of requests as we're scrolling through Activities. 

> Put All Sort Order in Default List Order (I Think It is Planned)

3. I don't quite understand this one. Care to explain more?

**Comment by zend10** [comment]
Search bugs is fixed on v.1.1.3.

**Comment by ImPudding-tech** [comment]
![Screenshot_20200910_072849_com.zen.alchan.jpg](https://user-images.githubusercontent.com/65703094/92664938-e5a88980-f337-11ea-9f90-f3f5e5e58c47.jpg)
![Screenshot_20200910_072832_com.zen.alchan.jpg](https://user-images.githubusercontent.com/65703094/92664944-e80ae380-f337-11ea-871b-dcd40715e8fd.jpg)

Oh Men... I Always Open A Issue.. 😂

**Comment by zend10** [comment]
Oh, that one. Default list order is following AniList settings and AniList only allows 4 of them afaik.
