### ISSUE TITLE
BUG/REQUEST 1.2

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#19]
While Im Adding Manga/Anime To my List I saw Alot Of  Features Need and Bugs of Al-chan. 

**Features Request**

- add X Button inside or outside or beside the Search Pannel (so it is easier to erase the last thing i searched)

- the Filter Choice "hide Manga/Anime On My List"  is There Posibility that If I Add Anime/manga in my list it will automatically Hide... (Because it Remains Show until i Refresh) 

- In List Editor (how about Automatically Showup keyboard When it needs the it) because It Only Shows Up if You Click The Fill Up Blank) 

- in Seasonal Chart How about put the Filter inside the three dots Like You did in Anime/Manga List and in
  "Season Sort" Why Theres no All. It is To Prevent Us From Lagging? 🤔

**BUGS**
- The Bug In List Setting Still there. I think it is because I have Alot of Custom Anime List ( I Click "reset to default" nothings Happen) 

- The Search bug Still Cant search Synonyms in Anime/manga in my list 

- in "releasing Today" I Dont quite get the sort can you Make it like Airing next 😊

******Btw... I love the Latest UPDATE... ❤️❤️******

I BECAME REGULAR HERE.. 🤣🤣 (IT IS BECAUSE I LOVE YOUR APP AND I LIKE TO Give you MORE Ideas)

[THE OTHER FEATURE REQUEST ARE MY SHOWER THOUGHTS]

Im Handsome

**Comment by ImPudding-tech** [comment]
> While Im Adding Manga/Anime To my List I saw Alot Of  Features Need and Bugs of Al-chan. 
> 
> 
> **Features Request**
> 
> - add X Button inside or outside or beside the Search Pannel (so it is easier to erase)
> 
> - the Filter Choice "hide Manga/Anime On My List"  is There Posibility that If I Add Anime/manga in my list it will automatically Hide... (Because it Remains Show until i Refresh) (In Seasonal 
> 
> - In List Editor (how about Automatically Showup keyboard When it needs the it) because It Only Shows Up if You Click The Fill Up Blank) 
> 
> - why Not Group The "Hide Manga/Anime On My List" and "Show Manga/Anime On My List" Like you Did With The Other ( I Think Its Planned because It is Related to Better FILTER) 
> 
> **BUGS**
> - The Bug In List Setting Still there. I think it is because I have Alot of Custom Anime List ( I Click "reset to default" nothings Happen) 
> 
> - The Search Still Cant search Synonyms 
> 
> ******Btw... I love the Latest UPDATE... ❤️❤️******
> 
> I BECAME REGULAR HERE.. 🤣🤣 (IT IS BECAUSE I LOVE YOUR APP AND I LIKE TO IMPROVED MORE)

**Comment by zend10** [comment]
1. Alright.

2. This is definitely complicated. I'll have to pass this one.

3. Good idea.

4. There are not as many filter in Seasonal as in Anime List, and it's faster to change between season if we put the filter at the front. What do you mean by "All" in Season Sort?

5. Not working? Let me see what's right now and what happens after you reset to default?

6. Ah right, I handled for other titles (romaji, english, native) but not synonyms. Going to handle synonyms in the next update as well.

7. I don't quite understand this one. Please explain again.

Thanks for the feedback. It's been a huge help. :)

**Comment by zend10** [comment]
Okay, I actually understand what you mean with point 7 now. You want it sorted by airing time. Alright.

**Comment by ImPudding-tech** [comment]
4. I mean Change The Default Season To Any

![Screenshot_20200912_080640.jpg](https://user-images.githubusercontent.com/65703094/92982013-03f4bd80-f4cf-11ea-9bcd-4a548e5a0512.jpg)![Screenshot_20200912_080658.jpg](https://user-images.githubusercontent.com/65703094/92982021-0ce58f00-f4cf-11ea-9c53-3cbf3a9d4a12.jpg)

**Comment by zend10** [comment]
Oh, no, it's not intended to follow AniList. It's closer to AniChart more than anything. The default should be the current season.

**Comment by ImPudding-tech** [comment]
How about 
It is Possile to Make Year Range Select...

For example I Like To Choose Anime Between 2011 and 2013

**Comment by ImPudding-tech** [comment]
Also...
SORT By "EPISODE BEHIND"...
IF IT IS OK

**Comment by zend10** [comment]
Why though? Doesn't seem very helpful.

**Comment by ImPudding-tech** [comment]
Then How About Gaps Between Priorities... Something Like This.... (its Hard to Explain If I Dont Have A Photo, That why i edited it 😂😂)
![PicsArt_09-27-06 32 11](https://user-images.githubusercontent.com/65703094/94362726-fc98fb00-00ef-11eb-8b84-c0700502676c.png)

**Comment by zend10** [comment]
It takes quite a lot to change the current app to show it like that. We have sort by priority already and I'm working on so that we can filter by priority as well.

**Comment by zend10** [comment]
Everything that I said would be implemented has been implemented on v.1.1.5. Also want to point out not all dialog will show the keyboard automatically in List Editor. Only for some of them.

**Comment by ImPudding-tech** [comment]
Oh.. Men... 😢...
