### ISSUE TITLE
Better Filter

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#2]
Is There Posibility that... 
CAN YOU FILTER IT BY Day..

**Comment by zend10** [comment]
I can't understand what do you mean by filter by day.

**Comment by ImPudding-tech** [comment]
I mean... Something Like This....

![Screenshot_20200722_140640_me livechart android](https://user-images.githubusercontent.com/65703094/88140600-9d68c700-cc24-11ea-8c5d-dd1c3d0f39cb.jpg)

It shows the Anime Airing That Day...

**Comment by zend10** [comment]
It should be doable. Do we really need it though? Especially when we already have Releasing Today section at Home?

**Comment by zend10** [comment]
It's implemented on v.1.1.0. 🎉
