### ISSUE TITLE
The app works fatal in landscape mode

### ISSUE THREAD

**Issue by taksumaki** [zend10/AL-chan#20]
I was curious to know how the application worked in landscape mode and I was very surprised, the application cannot be used like that, and not for reasons of design of the activities, etc.

If not because it gets super slow, I don't know how to scroll anywhere because it works with super lag, I don't understand why the truth is, you could try it too. So to know if it is just my phone or is it the application itself that has that failure that works super slow in landscape mode.

**Comment by zend10** [comment]
I'm pretty certain it's nothing to do with landscape mode. It's extra laggy in the latest update (v.1.1.3) because I was trying to "fix" the crashing issue in markdown (Activity and Bio), but it ends up worse. Please try again once the new update (v.1.1.4) is out.

**Comment by taksumaki** [comment]
Hmm, I suppose so because it only happens to me if I put the application in landscape mode, if I don't use it like that the application works normally.

**Comment by zend10** [comment]
I have tried using the landscape mode and it's just fine. Should be just a coincidence.

Say, if you open from external link straight to anime page and use the landscape mode, it shouldn't be laggy. Try click on this link and open from AL-chan, then use landscape mode, it should be fine:
https://anilist.co/anime/108632/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season/

The laggy issue is caused by huge image people use in their Activity or Bio. I haven't been able to handle it yet so far.

**Comment by taksumaki** [comment]
No, I do not mean the anime view, if not the main page, the initial place where the application takes when you open it. Where are the Tabs of "Home", "Anime", etc.

**Comment by zend10** [comment]
Yeah, that's it. The lag has nothing to do with landscape. It's certainly because of the Activities in Social tab. The new update (v.1.1.4) should return it back to as before I tried to "fix" it. Please try it again once the update is out.

**Comment by taksumaki** [comment]
Just update to AL-Chan version 1.1.4 and the problem you lost. I attach a video about what the problem is and I better understand the problem.

You can see a video example at the following link:
https://streamable.com/6sn0xe

**Comment by zend10** [comment]
I'll look into it, but please help me clarify again, since I can't really reproduce the lag:
1. Does the lag disappears if you change back to portrait mode afterwards?
2. What about opening the app directly in landscape mode? And what if you change it to portrait mode afterwards?
3. Is it only happening to this app?

**Comment by taksumaki** [comment]
1. No, the error persists only that it does not happen with vertical mode, but if I put it back horizontally, the Lag returns. That means that it only happens in landscape mode and it is there all the time, it is never fixed.

2. I just tried and the same thing happens, although it will be directly horizontal and then I change it to vertical, when putting it horizontally again the error persists.

3. Yes, only in this application, in no other.

I have noticed that it happens when I scroll down and being close to an image the Lag begins, for example, in the "Home" tab in the header it works normally, but I just get closer to an image when I am scrolling down the lag begins . As in the other sections.

Take note of this: The error is not fixed if I put it vertically and then horizontally again, the error always persists no matter how many times I try.

**Comment by zend10** [comment]
Well, this is very weird indeed. Let me try to look more into it. Thank you for your time.

**Comment by taksumaki** [comment]
I had a similar experience making an application for Android and it was because of the resolution of the images, I don't know if that information could help you, maybe you could optimize the images, I don't know. Optimizing the way they are displayed so that it doesn't appear at full resolution without losing quality might help.

**Comment by zend10** [comment]
Yeah, I'll need to look for more possible problem.

**Comment by zend10** [comment]
@taksumaki Would you mind trying version v.1.1.5 and see if there's any improvement?

**Comment by taksumaki** [comment]
Yes, the problem has been solved, there is no longer lag when used in landscape mode, perfect

**Comment by zend10** [comment]
Very glad to hear it. Thanks for your help. Appreciate it.
