### ISSUE TITLE
[suggestion] separate the "sort" option from "filter" screen in the manga/anime list

### ISSUE THREAD

**Issue by Sam-Oak** [zend10/AL-chan#21]
my suggestion is that the "sort" function has its own button for quick access.

**Comment by zend10** [comment]
I'm not very sure about this yet. Sure if you only want to sort the list but not filtering it. What about if you want to sort and filter at the same time? The current one will be faster. I have no idea what people are using more usually.

**Comment by Sam-Oak** [comment]
after I think for a while, I think this really doesn't need to be separated, so I'm going to close this issue
