### ISSUE TITLE
(Suggestion) - Search by pressing a Tag on an Anime Page and Color Spoiler Tags

### ISSUE THREAD

**Issue by ElFrostburnMC** [zend10/AL-chan#23]
-When in an Anime (or Manga) information page, if you press a Tag like these:
![IMG_20200927_135400](https://user-images.githubusercontent.com/65023891/94364496-fc860480-00c9-11eb-8f3b-f515f4a87167.jpg)
![IMG_20200927_135438](https://user-images.githubusercontent.com/65023891/94364498-fdb73180-00c9-11eb-8894-6fbfb495f538.jpg)
I think it would be a good idea if they show Anime/Manga with the same Tag in order to easily find more anime

-Show Spoiler Tags in a different color in order to see them better:
>This is the one without spoilers:
![IMG_20200927_135438](https://user-images.githubusercontent.com/65023891/94364617-fb090c00-00ca-11eb-841d-c9f58d6af29f.jpg)
>This is the one with spoilers:
![IMG_20200927_135448](https://user-images.githubusercontent.com/65023891/94364619-02c8b080-00cb-11eb-9df3-da24671e3043.jpg)

Feel free to ask if you have any doubts about the suggestion ^^

**Comment by zend10** [comment]
Actually funny I have it in my TODO for quite a while.

https://github.com/zend10/AL-chan/blob/f96f7621d0995adbe6d156be92b8eab0317e6e5a/app/src/main/java/com/zen/alchan/ui/browse/media/overview/MediaOverviewFragment.kt#L398

Yeah, I'm working on Tag feature at the moment so I think I'll implement it finally.

**Comment by zend10** [comment]
Implemented on v.1.1.5. You can even click on the Genre and Season in that page now.
