### ISSUE TITLE
Feature requests [View all list at once]

### ISSUE THREAD

**Issue by NetherKing1357** [zend10/AL-chan#25]
Hi, I've been using this ap for couple of hours now and I'd like some features implemented, could you check out if these are possible?

1. Set a default screen on app open: I'd prefer if the app opened to the anime tab/screen rather than Home.
2. Add an option to view all anime/manga instead of just the 6 options (Watching, Planning, Completed etc.)
![Screenshot_2020-10-04-18-47-56-493_com zen alchan](https://user-images.githubusercontent.com/31373161/95016808-016f2900-0673-11eb-8e99-875122f0de84.jpg)

3. Search searches all anime and not just the ones in the current filter of Watching, Planning, Completed etc.

4. Make the selection box for the Media page larger: it is too easy to go to the edit details page because the hit box for going to Media page is very narrow (just the name of the anime) in the List view. Otherwise, an option to switch between opening media and editing pages on hitting the name of the anime would be appreciated.
5. If there are changes made in settings or list settings and the back button is pressed, please give a save settings dialogue rather than quitting without saving

Additionally does the app allow you to write reviews for anime? I can't seem to find this feature anywhere.

Thank you for making an amazing app!

**Comment by Sam-Oak** [comment]
in 4, maybe it might be better to click on the cover to open

**Comment by zend10** [comment]
1. Is it really necessary though? It's just one swipe away. I mean, unlike using Drawer where you have to open the drawer, and click on it. When using Bottom Navigation, all of the menu are just one click away and for anime list or manga list, you can just swipe them once or twice.

2. I'm not very sure about implementing this one. It's a huge change and in my opinion, doesn't make the whole experience better. Like, what's the purpose of showing all directly? Showing all means providing this huge chunk of information all at once and it can be more confusing than helpful. I might be wrong here, convince me why this is necessary and I might consider it.

3. How would you suggest it's done?

4. Alright, I'll probably make it opening the media page by clicking the cover as Sam-Oak suggest it.

5. Alright. Seems like it can be applied to various places like list editor page and write activity page.

6. Not at the moment, but this one seems important so I'll add it to the development plan.

**Comment by NetherKing1357** [comment]
The view all option is available both on desktop and mobile version of the AniList website (as the All List) and will aid in consistency of the UI/UX across all platforms of usage.

![image](https://user-images.githubusercontent.com/31373161/95068052-59189d80-0722-11eb-9f7a-8a12146ca9df.png)

 I'd regard this as important since the user is most likely coming from the website to the app and will expect the same UI/UX. The option is also available on other anime list sites such as Kitsu and MAL. If the concern is on information overload you could group the anime by List, as in the site (see the above picture). On a more personal note, I've gotten used to seeing all my manga together, as that's how it is in my manga reader app as well as the previous sites and apps I've used to track my watchlist. Additionally having an All Anime list would make implementing 3 easier since the search could just pull from the list generated by the all anime option.

My ideal use case would be typing out a string and having results from all lists show up in the same tab (Anime/Manga). The exact implementation would depend on the AL API. Since I'm not familiar with Kotlin I can't help much with the actual code, but if the lists are some kind of JSON or structure I'd imagine there'd be a built-in method to append the individual lists and use the output object to run the search. A quick and dirty implementation would be putting a button to see all results, which redirects the user to the home tab search and applies an anime/manga filter and runs the search with the same string. An example from [zunjae/Anyme](https://github.com/zunjae/AnYme):

![image](https://user-images.githubusercontent.com/31373161/95069546-75b5d500-0724-11eb-856b-d8a3c3c20848.png)

Another quick request on the search: the search results don't refresh unless the string is changed, which causes an issue if you change list after typing out the string. Could you retrigger the search when Enter is hit and when anime information is saved, instead of waiting for a string update? This problem is also present in the search in the home screen, where the search results don't register changes in the anime status - for example if you search for an anime and add it, the Planning indicator doesn't show unless you change the search string or exit the search entirely and search again.

Fair point on the first issue, and thanks for the quick response!

**Comment by zend10** [comment]
Alright. I'll consider it, no promise. It's certainly an option that is good to have.

**Comment by zend10** [comment]
Will be implemented in the next update:
1. "All" list
2. Save dialog

Implemented in v.1.1.9:
1. Click on cover to open media
2. Write, edit, delete review

**Comment by zend10** [comment]
Will be implemented in the next update:
1. Save dialog

Implemented in v.1.2.5:
1. "All" list implemented.

**Comment by zend10** [comment]
I'll just close this now. If still needed, can create a new thread for it.
