### ISSUE TITLE
BUGS/REQUEST/SUGGESTION 1.3

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#26]
Yoss.... Im back...
I have a Suggestion
Instead of separate the include and exclude... Can you make it into... One...
If you click Once It will Became Include.. But if you Click Twice It will Became Exclude
(Something Like This...) 

![Screenshot_20201006_154208](https://user-images.githubusercontent.com/65703094/95172925-92b4db80-07ea-11eb-9873-7cce225c6444.jpg)

![Screenshot_20201006_154136](https://user-images.githubusercontent.com/65703094/95172923-921c4500-07ea-11eb-8ea7-883b8a9c28ef.jpg)

And Also Separate The countries in Readable on... 
![Screenshot_20201006_153412_com zen alchan](https://user-images.githubusercontent.com/65703094/95173193-efb09180-07ea-11eb-9949-67d1637e808e.jpg)

And Also Instead Of showing Saved... It Kept Showing HTTP 500... I DONT KNOW IF MY PHONE HAVE THE PROBLEM...(Fixed In Hotfix 1.1.6)
![Screenshot_20201006_154634_com zen alchan](https://user-images.githubusercontent.com/65703094/95173419-38684a80-07eb-11eb-96e6-e26fd02dc6ad.jpg)
..

**Comment by zend10** [comment]
Maybe not this time. If I do want to change the current way, I have different idea from that checkbox.
