### ISSUE TITLE
Transparent background avatars display with white background

### ISSUE THREAD

**Issue by Davoleo** [zend10/AL-chan#27]
The title basically says it all, I have a png avatar that has a transparent background and this works well on the website which has support for transparent background although it looks like this on the app:
![profile](https://user-images.githubusercontent.com/24458276/96245834-12d7ff80-0fa8-11eb-8be2-af9966033d7c.jpeg)

**Comment by zend10** [comment]
You can remove the white background for Profile page in App Settings. Simply uncheck "Add white background to circular avatar".

**Comment by Davoleo** [comment]
ah ok sorry, didn't know that
