### ISSUE TITLE
[Minor Suggestion] Status Bar could be transparent

### ISSUE THREAD

**Issue by Davoleo** [zend10/AL-chan#28]
It would make page a bit more consistent if you saw the the anime background image color but a bit darkened, although I can understand the choice of keeping it like this to avoid readability issues

Oh yeah I guess I'll mention it: it's kind of similar to #10 although I'm using Android 9 and I'm looking for a behaviour similar to how it looks on apps like Spotify (if you look at the status bar it just is a semi-transparent black color that applies to whatever is below the status bar layer)

![status_bar](https://user-images.githubusercontent.com/24458276/96247132-fccb3e80-0fa9-11eb-9a77-7d8e95b9b854.jpeg)

**Comment by zend10** [comment]
I'm planning to make it edge to edge for all Android version if possible. I'm having a problem with it right now but I'll make sure to come back to it again.

**Comment by zend10** [comment]
Not exactly transparent status bar, but more like that behavior in #10. Implemented in v.1.2.0.
