### ISSUE TITLE
Issue with reaching Anime details page

### ISSUE THREAD

**Issue by Davoleo** [zend10/AL-chan#29]
If I didn't miss another shortcut to reach it, this is the only way of reaching the anime details page from an entry in your list: 
https://streamable.com/u47pur
It's a bit complicated from a user point of view having to go through multiple steps and clicking the title label of the anime from the Anime Entry editor activity

A solution to this could be:
- Having long press still open, either the entry editor activity/modal
- Having a standard/short press on the entry open the entry details activity instead of the entry editor activity
- and last but not least maybe add a button in the anime details activity to open the entry editor activity/modal

This way there are still 2 ways of accessing the entry editor while keeping the anime details page still accessible in an easy and direct way

Keep up the good work on this app, I really enjoy it, the design is consistent and it's one of the most feature complete app out of all apps of this kind!

I'll gladly contribute more, even code-wise if you need a hand, once I manage to get some free time, since University tends to get in the way :P

**Comment by Sam-Oak** [comment]
a suggestion i made on issue #25 is to click on cover to open the details page

**Comment by zend10** [comment]
What Sam-Oak said.

Also, at the moment, you can click on the title to open the anime page. Probably not obvious enough, if it's in primary colour, it can most likely be clicked.
