### ISSUE TITLE
[Bug] my status on the "friends list" on an anime page is occupying a large space

### ISSUE THREAD

**Issue by Sam-Oak** [zend10/AL-chan#3]
this appears when the series is on my list and has a score
![Screenshot_20200715-161753](https://user-images.githubusercontent.com/62823895/87604937-f2f61e80-c6ce-11ea-84d2-7a2245d2c465.jpg)

**Comment by zend10** [comment]
Ah yes, this needs fixing.

**Comment by zend10** [comment]
It's fixed on v.1.1.0. 🎉
