### ISSUE TITLE
[Suggestions] Search tool and List type (Persist preference change)

### ISSUE THREAD

**Issue by ian-vtr** [zend10/AL-chan#30]
In my opinion, I don't see why having two search options on the home screen. sometimes I get confused and click on the search tab (top) and I don't have the option of filters. It would be better if the two were together, that is, remove the explore button and place the filter options in the search tab.
![IMG_20201109_231554](https://user-images.githubusercontent.com/74222213/98619699-8c7eb700-22e2-11eb-93d4-860204a57500.jpg)
The list case I refer to the seasonal chart. I prefer the grid option, but every time I go there I have to change it because the linear option is permanent. It would be better if this option was fixed, like the anime list.
![IMG_20201109_231512](https://user-images.githubusercontent.com/74222213/98619929-f9924c80-22e2-11eb-8aa7-8ae14d7c5c94.jpg)
Thanks. (I apologize if I have an English error, I used google translator)

**Comment by zend10** [comment]
1. Removing Explore is definitely a no. Search and Explore have different behavior. For example, if you open Explore Character page, you'll be shown directly list of characters ordered by popularity. Meanwhile, if you open Search page, you'll not be shown anything. Although it might not seem significant, it just makes more sense UX-wise to open Search page to do quick search and Explore page to.. explore.

2. Hmm.. yeah this might be good, will do.
