### ISSUE TITLE
[Suggestion] Release app on F-droid

### ISSUE THREAD

**Issue by TuxKruger** [zend10/AL-chan#33]
Hi dev,

I have been using AL-chan for a while now. I recently got to know that the app is open-source.
It would be really nice to see the app (without non-free dependencies) on F-droid repo. Not only it will benefit the users who only use apps from F-droid and IzzyOnDroid but it will also help you in reaching more users who can give their feedback and contribute in this app's development in some way or another.
Here are some useful links:
https://f-droid.org/en/about/
https://f-droid.org/en/docs/FAQ_-_App_Developers/

**Comment by zend10** [comment]
Unfortunately no, if it's as simple as submitting an APK, sure, but it's not, I have to follow all their guideline and it's not as straightforward as I want it to be.

**Comment by TuxKruger** [comment]
Well then it can't be helped if you are finding it uncomfortable. Please reconsider it sometime.

**Comment by rakshazi** [comment]
Came here with the same proposal. Well, I hope you will change your mind in future
