### ISSUE TITLE
Localization Platforms

### ISSUE THREAD

**Issue by RickyM7** [zend10/AL-chan#34]
It would be great if your project were added to some localization platform, such as [Crowdin](https://crowdin.com/), [WebLate](https://weblate.org/), [POEditor](https://poeditor.com/) or [Transifex](https://www.transifex.com/). These platforms have free plans and make the work of translators much easier.

Note: I saw in PR #12 that you do not plan to provide multi-language support at the moment because of several things and I totally respect that, I just ask you to take a look at these platforms (if you do not know them yet) and think about the possibility of using any of these for the translation of your project.
Thank you for your great work.

**Comment by zend10** [comment]
Yeah, I'm still not very convinced with supporting other languages to this day. Also AniList's contents are all in English for now, like the anime description for example. Almost no point in translating all the menu but the contents are all still in English.

I wouldn't totally write it off, but supporting other languages is not in my priority at the moment.

**Comment by RickyM7** [comment]
I think having the app translated, even if the content itself is in another language is still something very useful. [MoeList](https://github.com/axiel7/MoeList) for example is a MAL client and even if the content itself is in English, having the interface translated makes the platform easier to use. Anyway I completely understand your point of view.
Btw, in case you want to add a multi-language support, I will gladly help translate your project into my native language. Thank you.
