### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ian-vtr** [zend10/AL-chan#35]
Hello, I don't know if it's my phone's problem or not, but I noticed some visual bugs:
![IMG_20201228_172106](https://user-images.githubusercontent.com/74222213/103241224-5a2c2600-4931-11eb-9c34-2be7ec59af83.jpg)
![IMG_20201228_172142](https://user-images.githubusercontent.com/74222213/103241226-5c8e8000-4931-11eb-81b2-a5e4306b8e1e.jpg)
![IMG_20201228_172037](https://user-images.githubusercontent.com/74222213/103241235-5f897080-4931-11eb-8b58-7378cc594598.jpg)
![IMG_20201228_172055](https://user-images.githubusercontent.com/74222213/103241242-631cf780-4931-11eb-9d89-90e844c08e32.jpg)
![IMG_20201228_172158](https://user-images.githubusercontent.com/74222213/103241252-6617e800-4931-11eb-89e0-cdeb76fd9048.jpg)

Some bugs also happen in the anime information.  sometimes I will see information from an anime, I leave them and go to another anime, this happens:
![IMG_20201228_172522](https://user-images.githubusercontent.com/74222213/103241348-ac6d4700-4931-11eb-8243-6b791472c387.jpg)

And sometimes when I go to see information about an anime, it happens (most of the time it happens when I enter different animes in a short period of time):
![Screenshot_2020-12-28-17-22-52-680_com zen alchan](https://user-images.githubusercontent.com/74222213/103241405-e2123000-4931-11eb-880c-220348c5174f.jpg)

Thanks.

> 

>

**Comment by zend10** [comment]
Sorry for taking my time with to reply to this. I was taking a break with maintaining the app.

- The preview is not really a bug. I just didn't handle it, but I'll see if I can manage to get it to full screen as well.
- As for those characters showing wrongly, it could happen when we're navigating between series quickly. I'll see if I can do something about it.
- And for the 429, yes, it's hitting the rate limit. My plan is to reduce the amount of different requests in a page and just merge some of them into one. Hopefully it can help with this rate limit problem.

**Comment by zend10** [comment]
Do you know how to easily replicate that wrong characters issue?

**Comment by ian-vtr** [comment]
Try to enter a page of an anime, the moment the page starts to load, exit it and enter the page of another different anime quickly.  Sometimes this happens, sometimes not.

**Comment by zend10** [comment]
Thanks, this is very helpful.

**Comment by zend10** [comment]
The rate limit issue is very problematic. My app's design requires me to do many concurrent requests (around 9 of them) in each anime/manga page.

At this point, probably can only be fixed if there will ever be AL-chan v.2.0.

But I'll make the error message clearer for now so people know what's going on.
