### ISSUE TITLE
[Small Favor] Music Info Copy

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#38]
When long Press or a Song.. 
It will Show another Dialog with Title And Artist and A Copy Beside. (So It is Easier to Copy the  Title and Artist) 

Something like this

| Copy |  (Title)       Touch You.         |
| Copy | (Artist)        Shiritsu MoriMouri Gakuen Senshun      |
(I dont Know How To Edit. SO i edit It With My Gallery.) 
![Screenshot_20210128_221638](https://user-images.githubusercontent.com/65703094/106150682-88ae5280-61b6-11eb-8706-d4001ffb2bbf.jpg)

I dont know how to Explain.. But i hope You Understand.
If you don't understand Feel Free to Close.... 😂😂😂

**Comment by zend10** [comment]
Lol sure. Probably not this exact same way you're suggesting but we'll be able to copy it.

**Comment by zend10** [comment]
I'm very sorry that I'm not going to implement this anymore. :(
