### ISSUE TITLE
[Suggestion] Option to hide the score indicator

### ISSUE THREAD

**Issue by ian-vtr** [zend10/AL-chan#39]
Hi, I don't know if it's just me, but sometimes I feel a little uncomfortable with "?" in the score indicator (sometimes I don't score anime, sometimes I do)...
![IMG_20210131_124045](https://user-images.githubusercontent.com/74222213/106389346-9e439800-63c1-11eb-8ccd-2bc5a6c4080d.jpg)
![IMG_20210131_124021](https://user-images.githubusercontent.com/74222213/106389350-9f74c500-63c1-11eb-9a12-057e85ce8dee.jpg)
I know that there is a way to hide the volume indicator in the manga list, so I think this option will not be so difficult.
By the way, when showing the score indicator, I think it would be better to just indicate the star symbol without this "?", Then when you edit, the score appears.

**Comment by zend10** [comment]
It's certainly possible. How about I make an option so that it's not shown when there's no score instead?

**Comment by ian-vtr** [comment]
> It's certainly possible. How about I make an option so that it's not shown when there's no score instead?

Yeah, I support that idea
