### ISSUE TITLE
Persist anime/manga list filter across application restarts.

### ISSUE THREAD

**Issue by Mifuto** [zend10/AL-chan#41]
After the recent update AL-chan shows all anime/manga in your anime/manga list by default and there's no way to change it (permanently). Personally I liked the way AL-chan showed anime/manga list before the recent update I think it's cleaner/better. So it would nice if you gave users a way to choose default filter for anime/manga list or persist anime/manga list filter across application restarts.

**Comment by zend10** [comment]
Yes, I'll definitely be prioritizing this one.
