### ISSUE TITLE
2 bugs (actually 1)

### ISSUE THREAD

**Issue by Afurodi** [zend10/AL-chan#43]
1. Skips update of last episode when automatically moving to completed

When you update your Anime with the last episode the "Do you want to move this Anime into Completed? " option pops up.
If you however choose "Move" the last episode won't get updated.
Means that in social there stands "Watched 1-23 of [Anime]" followed by "Completed [Anime]". 
If you however choose the "Stay" option and then manually move the series into completed it shows "Watched 1-24 of [Anime]" followed by the same. (Assuming Anime has 24 episodes)
Shouldn't be annoying to fix, while also isn't important as it apparently doesn't affect you stats.
Apparently same with Manga and 1 episode Anime aka. movies as I just tested. 

 2. Weird score distribution visuals

_(I failed. It's already known. I checked before for this issue and oversaw it. Now that i checked again I noticed that it was mentioned in literally the last post. The rest from here is skipable and only about the score thing. Have a great day!)_ 

I don't know if this is a bug or a feature but I guess the first one as it's confusing.
If you go to your score distribution it shows your scores in a weird way.
I'll link 2 pictures to make it easier to understand. 

AL-Chan: https://i.imgur.com/2TTu5Zk.jpg
AniList: https://i.imgur.com/l4zIvQk.jpg

It most likely has something to do with the 0.5 (as I vaguely recall testing that) but it's really weird if that'd be right.
It's as if 9.5 ~ 10 but at the same time 8.5 ~! 9.
2, 4, 6, 8, (10) and 1, 3, 5, 7, (9) are this way (actually I don't know if you can rate 0.5 so maybe 1 doesn't have this issue)
This makes the score look disproportionate.
Also this maybe is known already as its actually a bit older, sorry if it is.

And have a good day!

**Comment by zend10** [comment]
Hmm I think it's actually how AniList work. If we set to Completed, we'll only get "Completed [Anime]" activity. You can try so in AniList directly. If you want it to display "Watched 1-24 of [Anime]", you have to make an API call twice. One to update the progress and then followed by change the status. I don't think I should do that.
