### ISSUE TITLE
[Feature Request] - Disable / Hide Manga tab, overall experience

### ISSUE THREAD

**Issue by Dschogo** [zend10/AL-chan#44]
- [ ] 1. It would be nice if you could hide the manga tab / list in the bottom as an option in the settings.
Furthermore maybe a second option to hide the mangas in the Home tab as well.  (Like trending manga)
(Maybe for only manga readers everything other way round too)

- [ ] 2. When clicking a trailer don't ask every time to open app/browser. Just ask once. (Maybe an option to change this behavior?)

- [ ] 3. When clicking through relations or anything and go back to the previous page. Let them be cached (reduce network load) and including the scrollposition of the site makes the experience smoother. (Maybe also as an option for those with low power devices / ram)

- [ ] 4. Clicking on the description of an entry could open it, instead of only the arrow. (Closing can stick with the arrow only)

- [ ] 5. While swiping sideways disable swipe down to refresh (reloading). (Noticed that till now only in the calendar)

everything pretty minor requests but I think it would increase the user experience and shouldn't be that hard to implement.

**Comment by zend10** [comment]
Hmm not bad suggestion. Especially about caching, it's in my priority. But this will take some time.

**Comment by zend10** [comment]
I'll close this for now. If still needed, can create each feature in separate thread for easier tracking.
