### ISSUE TITLE
Custom Lists in List Settings not showing everything

### ISSUE THREAD

**Issue by BaccanoMob** [zend10/AL-chan#45]
Hi,
Just a couple of feature requests.

1red. Adding a slide bar for the scoring would be convenient as in the priority bar rather than typing in the number? Or perhaps like a drop box function?

2blue. Could you possibly implement an autosave function when going back from the editing menu? (Well personally I'm new to anilist itself so I'm adding a ton of anime and manga and I'm half the time forgetting to click save when I finish)

And thanks for the hard work in making the app! It's been really helpful for me!!

![Screenshot_20210416-141528_AL-chan](https://user-images.githubusercontent.com/82655889/115023244-d20d6480-9ebe-11eb-9d2c-e204721e9d8e.jpg)

**Comment by BaccanoMob** [comment]
Adding another suggestion, is it possible to move the "Sort by" and "Order by" from the Filter menu to Customize list menu? So the list does not reset the order upon re-opening the app again.

**Comment by zend10** [comment]
1. I'm not sure about using slide bar to select score. How would we slide to 7.6, for example? If we're using 0-10 without decimal scoring system, we'll be given a number picker to pick our score. It's when we use 0-10 with decimal or 0-100 that we have no choice but to type. Slide bar doesn't work very well when there's decimal or when the range is too big.

2. Auto save is too dangerous. I would rather not.

3. Moving "Sort By" to Customize seems like a good idea.

**Comment by BaccanoMob** [comment]
Thanks for replying. I agree for the first two and hope to see the 3rd with one of the upcoming updates.

As a fourth one, in customise menu, is it possible to implement which lists (default and the custom ones) should be visible and the order it should be displayed in the anime/manga list in the app?

Personally most of the times I don't view the completed ones and because I have a few custom lists which I try to look at it frequently but they are at the bottom of the list.

**Comment by zend10** [comment]
Yes, it's indeed a bug. Still haven't got around to fix it.
