### ISSUE TITLE
build instructions and releases

### ISSUE THREAD

**Issue by benjaminBrownlee** [zend10/AL-chan#48]
It would be nice if releases of the app were tagged here and had APKs or build instructions (I am not an Android developer, but simply running `./gradlew assembleRelease` is not working for me).

**Comment by zend10** [comment]
You need to supply your own `google-services.json` gotten from Firebase first before you can build it.

**Comment by benjaminBrownlee** [comment]
Could you provide more info about which google services are needed and how they need to be configured? Also, do you have a list of build dependencies and a process that you take to run the build? I think these would all be great things to have in the README.

**Comment by zend10** [comment]
Not right now I guess. I really got my hands full at the moment.

As for now, you can follow this documentation to get the `google-services.json`: https://firebase.google.com/docs/android/setup

Then you simply need to rename the field `"package_name"` to `com.zen.alchan` or rename AL-chan's package name to whatever you want but make sure to match the name in the json file.

**Comment by benjaminBrownlee** [comment]
Well hopefully you find time. Let me know here when you do. I believe that build instructions, release tagging, etc. are essential components in an open source project that will make it easier for people to help contribute.

**Comment by zend10** [comment]
Yes, I understand your point.
