### ISSUE TITLE
Social Feature

### ISSUE THREAD

**Issue by hxpelessrxmantic** [zend10/AL-chan#51]
Okay, so I don't know if this is just for me and I've done something wrong but the social tab doesn't work for me at all. It used to but now it doesn't anymore.
![Screenshot_2021-05-08-20-08-31-33_61058300781f439b0e17c7b891337b23](https://user-images.githubusercontent.com/83874012/117543165-4c05b900-b039-11eb-99db-6609f74e3888.jpg)
Is there something I need to do for this to work again or...?

**Comment by zend10** [comment]
I have no idea why as of now tbh. I'll take a look why. As for now you can try relogin maybe.

**Comment by hxpelessrxmantic** [comment]
Hey, I did this and it's working again but it seems like when I log out, the best friends feature also resets...no problem tho...thanks for the suggested fix

**Comment by morning-paradigm** [comment]
This happened to me when I selected  'status'. I had to reset app data to fix this. 
![Screenshot_20210723-205744400](https://user-images.githubusercontent.com/39773982/126809931-d8962574-bf03-4063-89a7-e92f24336cef.jpg)
