### ISSUE TITLE
Editor Custom Lists don't follow specified order

### ISSUE THREAD

**Issue by smowtenshi** [zend10/AL-chan#52]
I have many lists in my anime and manga section and they're sorted in specified order of priority. I remember when it was working just fine, but for some time already they're just in order how they were added, not in a sorted one.

Here is shown how they look on a website:
![p0](https://files.catbox.moe/by4fta.jpg)

In the app settings:
![p1](https://files.catbox.moe/l3hyql.jpg)

And in app editor:
![p2](https://files.catbox.moe/s5ud77.jpg)

Despite being sorted correctly in the settings, they display wrongly in the editor.

**Comment by zend10** [comment]
Seems like I don't even sort it here in the editor in the first place. Makes more sense to have it sorted I guess.
