### ISSUE TITLE
[Feature Request] Hold down on title to copy 

### ISSUE THREAD

**Issue by onkoe** [zend10/AL-chan#55]
Tachiyomi, a manga/etc reader app for Android, has a feature that allows you to perform a long press on the title of a manga to copy its name for use elsewhere. I feel that it would work very well in this app too, and I find myself trying to do it quite often. I don't mind donating $20 or something if you need motivation. Thanks for the great app! :)

**Comment by onkoe** [comment]
By the way, this is partially a thing already in the info section, but it's not very obvious. I tested everywhere I found the title before finding this out. Hope this hopes future Googlers or whatever x)

**Comment by zend10** [comment]
I guess that makes sense. Currently, if it's in the text is in Primary (yellow) or Secondary (cyan), it probably can be clicked. Not all, but most of them.

Thanks for the good intention by the way.
