### ISSUE TITLE
[Feature Request] Anime and Manga in progress in Home tab

### ISSUE THREAD

**Issue by BaccanoMob** [zend10/AL-chan#56]
Pretty much self explanatory. Since I watch and read anime and manga simultaneously, it be convenient to have the anime and manga in progress entries in the home tab (preferably below "Releasing Today" or with an ability to customize the home tab as similar to lists).

**Comment by zend10** [comment]
I don't quite agree with this suggestion. It's just one click away to access your list. To have it in Home doesn't sound useful to me.

**Comment by BaccanoMob** [comment]
Right now, current home tab has a few search settings on top, releasing today and finally trending anime/manga. 

I open frequently to track anime and manga. Since I never see the trending anime and manga, I feel it be good to customise the home Tab to the user's liking from features from other tabs which you wanna look in one go. (Features like favourites, stats, Manga/anime in progress, custom lists maybe).

**Comment by N0D4N** [comment]
Maybe better solution will be to make default tab changeable like #57 suggests, instead of making home tab customizable?

**Comment by zend10** [comment]
I'll think more about customization for Home. But even then I doubt I'll add currently watching/reading series in Home.
