### ISSUE TITLE
Add filter for Adult Only in Calendar

### ISSUE THREAD

**Issue by BaccanoMob** [zend10/AL-chan#59]
"show only anime from current season" not working as intended (displays not found) while "Show adult content" displays all shows in the current season.

**Comment by zend10** [comment]
Yeah something breaks somehow.

**Comment by zend10** [comment]
Seems like things are fine now when I test it. Can you try again? @BaccanoMob

**Comment by BaccanoMob** [comment]
I tried it just now.

1. Show only anime in your watching and planning list - Works as intended
2. Show only anime from current season - Works as intended now
3. Show adult content - Works as intended now, It would be useful, if the title is marked "Adult" in the calendar menu itself as its difficult to differentiate among other titles.

Other than the suggestion, everything works fine now.

**Comment by zend10** [comment]
Yeah, your suggestion makes sense. I had difficulty myself when rechecking this. Thank you.

**Comment by BaccanoMob** [comment]
shall the title be changed to "Add 'Adult' label to respective entries in Calendar menu"?

Hope you test it out by the end of November (there are couple of shows that would be shown in the calendar as far as I checked)
