### ISSUE TITLE
Easier +1 Ep Buttonei

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#6]
I think You Need to Add this Buttons... Because I Have A lot of Anime Watching... And It's Hard to Find The Anime I am Watching..
![PicsArt_07-22-02 24 52](https://user-images.githubusercontent.com/65703094/88142111-837cb380-cc27-11ea-87fe-2fdf1651ab76.jpg)

**Comment by zend10** [comment]
I'm thinking of adding it to Releasing Today but not in Anime detail page. I can't see it being very useful and it's taking up the precious white space.

**Comment by zend10** [comment]
It's implemented on v.1.1.0. 🎉
