### ISSUE TITLE
[Feature request] Make custom lists first-class list types

### ISSUE THREAD

**Issue by N0D4N** [zend10/AL-chan#60]
Currently, there is no way to access manga only from certain custom list. So if user hides manga from status list he cant access such manga via anime/manga tab anymore, only from direct link/searching it by name etc. I think it would be nice to have custom lists alongside default status lists in anime/manga tab.

**Comment by zend10** [comment]
You can do that already. Add that manga to Custom List then hide it from status list.

**Comment by N0D4N** [comment]
I can't select any custom list from menu on screenshot, but i have them on my account: [link to one of them](https://anilist.co/user/N0D4N/mangalist/Wait%20for%20completion), and I can't access manga hidden from status lists from manga tab, in my case this is  "Fate/kaleid liner Prisma☆Illya 3rei!!"
![Screenshot_20210619-120711_AL-chan](https://user-images.githubusercontent.com/50947930/122637612-5a46fa80-d0f8-11eb-9d6d-a21c5560d2a1.jpg)

**Comment by zend10** [comment]
Looking weird now. If you go to List Settings, do you see your Custom List there? How about trying to "Reset to Default" the manga section order as well?

**Comment by N0D4N** [comment]
Reset to default fixed this. Thank you!
