### ISSUE TITLE
Suggestions(you may already know but still...) 

### ISSUE THREAD

**Issue by Imsleepyyy** [zend10/AL-chan#62]
I want these features when I check a certain anime before adding to my list.
First is reviews and social - 
<img src="https://files.catbox.moe/39az7e.jpg">
Second is Following and threads - 
<img src="https://files.catbox.moe/dlr2b0.jpg">

**Comment by zend10** [comment]
Other than Forum, we already have them all. Just swipe the menu.

**Comment by Imsleepyyy** [comment]
Bruh! I'm feeling so embarrassed now for suggesting this without looking into the app properly. I'm really sorry for this >~<

**Comment by zend10** [comment]
No worry. I'm well aware of the fact that some people miss it because on some screen, we can't see clearly it's scrollable. It's one of the things I'll be looking to redesign for v.2.0.
