### ISSUE TITLE
[Suggestion/Feature Request] Notes Searching  

### ISSUE THREAD

**Issue by SmokinRay01** [zend10/AL-chan#64]
It would be better if while searching through one's own manga/anime list, we could also do it with taking the 'Notes' into consideration also.
Like,
As in AniList website we ourselves cannot add the tags(without it being approved), we can simply put it in the 'Notes' and directly search for it in the 'My Anime/Manga List' (in the website).
It would really help alot. 
(Once again, I'm sry if this doesn't make sense...)
Thank you.

**Comment by zend10** [comment]
Honestly just found out we can search the note. Yup will do.
