### ISSUE TITLE
[Bug] Manga entry editor shows Total rewatches when clicking to change rereads count

### ISSUE THREAD

**Issue by N0D4N** [zend10/AL-chan#65]
When you change manga entry, by adding it to list, or editing it in list, when you click on `Total rereads` field to set count of total rereads, popup that are showing up is saying `Total rewatches`.
I believe bug lies in [this line](https://github.com/zend10/AL-chan/blob/ee56d54de3e8dbeaac86ddf5b9def90dda4ddc83/app/src/main/java/com/zen/alchan/ui/mangalist/editor/MangaListEditorActivity.kt#L444), and it should be changed to `R.string.total_rereads`.

**Comment by zend10** [comment]
Thanks for debugging it for me. I'm currertly working on v.2.0 and the approach is wholly different though. :)

**Comment by N0D4N** [comment]
Okay, thanks for info. I'll close it when v2 will be released, so others who will find this bug and would want to open an issue will be able to find this one, before creating new.
