### ISSUE TITLE
[Bug (?)]Total Anime/Manga

### ISSUE THREAD

**Issue by SmokinRay01** [zend10/AL-chan#66]
The 'Total Anime/Manga' shows wrong info...
There are various Sub-Lists that a person can make, so it would be better if only the *6 main lists that are provided by AniList would be taken into consideration.
* The 6 Category asked as 'Status' while adding a Manga/Anime in our list...
![Screenshot_20210708-003419](https://user-images.githubusercontent.com/86943042/124815104-7d8cf900-df84-11eb-88a2-174278be01cb.jpg)

If all the lists, i.e. 6 Main + Self-Made Category, are taken into consideration, then there is a overlapping between the the same Manga/Anime persent in different Category of List is taking place resulting in the total number of Anime/Manga becoming wrong(more).
Thank you.

**Comment by zend10** [comment]
I'll be changing the calculation in the future update. But at this moment, I'm following the number AniList provided. So, if the number is wrong, it's AniList's calculating it wrongly. I'm not very sure myself.
