### ISSUE TITLE
Show Relations between titles such as 'Contains/Compilations'

### ISSUE THREAD

**Issue by curche** [zend10/AL-chan#67]
Titles in Anilist are associated using Relations that are useful to identify Prequels, Sequels etc and have been very useful
Recently, I found that there is a new `Contains`/`Compilation` relation available; mainly seen it for One-shot compilation volumes wherein there's a separate entry for each one-shot and an entry for the Volume as well

The newer Values/ENUMs come from the Version 2 as listed on their [Reference Docs](https://anilist.github.io/ApiV2-GraphQL-Docs/):
| `MediaRelation` | Type of relation media has to its parent |
|---|---|
| `SOURCE` | Version 2 only. The source material the media was adapted from |
| `COMPILATION` | Version 2 only. |
| `CONTAINS` | Version 2 only. |

Examples:
[From Graphiql Interactive Editor](https://anilist.co/graphiql?query=%2Cquery%20(%24id%3A%20Int)%20%7B%0A%20%20Page(perPage%3A%2050)%20%7B%0A%20%20%20%20media(id%3A%20%24id%2C%20type%3A%20MANGA%2C%20format_not_in%3A%20%5BNOVEL%5D)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20title%20%7B%0A%20%20%20%20%20%20%20%20romaji%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20status%0A%20%20%20%20%20%20relations%20%7B%0A%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20title%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20romaji%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20relationType%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22id%22%3A%20105022%0A%7D)
[Datte Kimi wa Osananajimi](https://anilist.co/manga/105022/Datte-Kimi-wa-Osananajimi/)
[Hesomagari-Syndrome](https://anilist.co/manga/133756/Hesomagari-Syndrome/)
[Ai Sarete Miru (Warning: NSFW)](https://anilist.co/manga/128904/Ai-Sarete-Miru/)

**Comment by zend10** [comment]
Yes, I'm aware of this. I'm focusing my time on v.2.0 at the moment. This will come with v.2.0.
