### ISSUE TITLE
Custom default sorting method

### ISSUE THREAD

**Issue by debashisbiswas** [zend10/AL-chan#7]
When viewing anime and manga lists, content is always sorted by 'Score' by default. However, this may not always be the desired sorting method. This means the user must go to Filter -> Sort and change the sorting method every time they visit the list, because the default method can not be changed. 

A possible solution could be to add a setting to customize the default sorting method on the "Customize List" page.

**Comment by zend10** [comment]
It's possible to change default sorting order:
1. Go to Settings
2. Select List Settings
3. Change Default List Order

**Comment by debashisbiswas** [comment]
Didn't realize those settings were available as well :) sorry for the unnecessary request
