### ISSUE TITLE
Incorrect display of manga start date when date is unknown

### ISSUE THREAD

**Issue by N0D4N** [zend10/AL-chan#71]
Currently on manga with status Finished but without present start date like this https://anilist.co/manga/89246, app writes "TBA" at the top of the page, i believe this should be replaced with "unknown" or that field shouldnt be displayed at such case at all.

**Comment by zend10** [comment]
Hmm I didn't know such there's such data in AniList. Good find.

**Comment by N0D4N** [comment]
I assume a reason for the bug is - manga has no start/end data set, maybe its null, but its status is Finished, instead of Not Yet Released. app sees that no start/end data set assumes that manga's status is Not Yet Released and therefore displays TBA

**Comment by zend10** [comment]
Yes, surely that's what I did.
