### ISSUE TITLE
[Bug] List affinity info icons

### ISSUE THREAD

**Issue by Arrow420** [zend10/AL-chan#72]
After tapping the list affinity button, the little animation appears in the wrong place. 

Also, in the image the right icon displays the message "not enough shared manga to compute affinity" but it's the same color as the left icon which causes confusion.

![Screenshot_2021-07-24-00-07-44-057_com zen alchan](https://user-images.githubusercontent.com/37770973/126844133-6906c49c-7aa1-4062-9714-c446a0e6b67d.png)

**Comment by zend10** [comment]
I'll be doing this completely differently in v.2.0. I'll be closing this for now.
