### ISSUE TITLE
Custom Colors.

### ISSUE THREAD

**Issue by chief141** [zend10/AL-chan#74]
![Screenshot_2021_0824_133927](https://user-images.githubusercontent.com/59825803/130581260-54cb2c5d-3857-4c55-9b36-b2e8e563af21.png)
Ability to choose and select any color. ( Ability to customise colors of a theme )

**Comment by zend10** [comment]
I've looked through this and couldn't really find any elegant way to do it. If anyone can provide me with some convincing reference, I wouldn't rule it out.

**Comment by Dschogo** [comment]
searching elegant way = how to design the color picker?

im interpreting custom colors as: there are color regions, like primary secondary, text, description whatever, basically like now.
if then i recently saw vanced's one which was pretty cool:

![Screenshot_20210920-163400 (Klein)](https://user-images.githubusercontent.com/36862419/134021498-d4de6beb-ec93-4cc7-9e17-18d8289e7e5f.png)

To implement with themes: 
selecting any theme just overrides the current color values, clicking on one color circle opens a color picker.

**Comment by zend10** [comment]
The color picker is not the issue. My problem is I'm not sure how to apply it into every single screen without having to set them by myself manually.

**Comment by zend10** [comment]
I'll close this for now. Seems quite tough to do with my current knowledge.
