### ISSUE TITLE
[Feature Suggestion] Custom Links

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#75]
Hi Again.. I Think it is A Good Idea To Add Custom Link.(If It is Posible)
To Focus The Track While Watching/Reading . I Tjink it is A Good Idea To Add Custom link Which Is Us Will Provide The Link..
Example : I Want To Add A Link Directly To the "Mangadex" Which Is Not Provided by the Default Link. It is Posible To Add It Ourself. (Those links Are not Public, but It is Our Best Shortcut. to Go Directly To the Link Provided....
...
![Screenshot_20210911_085657](https://user-images.githubusercontent.com/65703094/132931032-478742d1-edb7-4780-bc7e-40e36b3af30f.jpg)

**Comment by zend10** [comment]
I'm not very certain if people would find this useful. I would imagine people would go to MangaDex directly instead.

**Comment by ImPudding-tech** [comment]
I Just Use Mamgadex To explain. It But How About If You Use It on Pirated site of Anime... Alot Of Ads.. It is Easier if You Add The Link of that Site. Then No More Search.. it will go Directly To the Provided Link...

**Comment by onkoe** [comment]
This is a feature that would need to be added to the AniList website and API before it could (or should, rather) appear in this app. In my view, AL-chan is intended to be a simple mobile front-end for the AniList service. For this reason, it generally avoids implenting things that use external services and APIs (especially inconsistent ones like Mangadex).
