### ISSUE TITLE
[Bug] Notes icon suddenly disappeared

### ISSUE THREAD

**Issue by SilverKnight-Z** [zend10/AL-chan#76]
Since a few hours ago, the notes icon that appears in the upper left corner of the image of each anime and manga, just disappeared. 

![Screenshot_20210923-205624_AL-chan.jpg](https://user-images.githubusercontent.com/82909608/134602523-ad950fda-b342-4a13-b926-e36f6f3ba5a9.jpg)

I opened the app normally as usual and the icons were gone. 

The only way to check notes is through the editor. I tried closing and reopening my session, but the icons are still gone. 

I don't know if it's because a few days ago the app suddenly told me that my session expired and forced me to log in again. 

My OS is Android 10 

Thanks for your attention and your great work. AL-chan is really excellent

**Comment by zend10** [comment]
You can re-enable it in Customise List. This happens because currently List Style is removed when we're logged out.

**Comment by SilverKnight-Z** [comment]
Oh yeah you were right, I didn't remember that. Thank you for your help and sorry to bother you
