### ISSUE TITLE
Add animethemes.moe as alternative for fetching OP/ED themes

### ISSUE THREAD

**Issue by curche** [zend10/AL-chan#82]
AnimeThemes, https://animethemes.moe, qouting their website, provides "A simple and consistent repository of anime opening and ending themes". I feel that this would be a good alternative (even replacement) to the current API used for fetching anime theme

Few highlights of the repository:
 - [indexed](https://old.reddit.com/r/AnimeThemes/wiki/anime_index) and kept up to date so as to provide *all* Opening/Ending themes for every anime possible
 - videos provided in .webm format: usually includes both original and cleaned (NC-OP/ED) themes
 - the videos are provided as direct links, usually embedable, and playable on phone either from Browser or using supported apps like mpv, vlc
 - provides an [API](https://staging.animethemes.moe/api/docs) for accessing OP/ED

Example: [Domestic Kanojo](https://anilist.co/anime/103139/Domestic-Girlfriend/) has a banger OP
 - Index entry: https://old.reddit.com/r/AnimeThemes/wiki/2019#wiki_domestic_na_kanojo
 - Cleaned OP (with no text credits) link: https://animethemes.moe/video/DomesticNaKanojo-OP1-NCBD1080.webm
 - API Query: single query using `anilistID` to fetch all opening/ending themes [click here](https://staging.animethemes.moe/api/anime?include=animesynonyms,series,animethemes,animethemes.animethemeentries.videos,animethemes.song,animethemes.song.artists,studios,images,resources&fields[anime]=id,name,slug,year&filter[has]=resources&filter[site]=AniList&filter[external_id]=103139)

### Other details
 - Rate limiting might be a problem considering the app has a large userbase: should be fine ig but perhaps best to talk with the devs at their discord server since I can't comment much about this
 - The API might not be that straightforward or include too much details. The above query example does provide one way to use Anilist ID to easily fetch all OP/ED and other details

**Comment by zend10** [comment]
I'll look into this more. Looks neat.
