### ISSUE TITLE
Filter out manga's translation staff not on manga page

### ISSUE THREAD

**Issue by N0D4N** [zend10/AL-chan#83]
In several places like homepage and explore manga page, app shows staff related to manga. Normally it is mangakas and original creators. However for licensed manga AniList returns staff related to manga's "localization/translation", such as letterers, translators, touch up artist, etc. But in my opinion, with all due respect, such staff shouldnt be showing anywhere except on manga page itself. In other places displayed staff should only be mangakas, perhaps their assistants and original creators of source material. So app should filter staff by their roles.   
Here are few examples when large amount of staff messes up app's look:
Explore page
<img src="https://user-images.githubusercontent.com/50947930/142506121-8b6c1852-d164-43b5-b9dc-ea564bee49ce.jpg" width="20%" height="20%">

Homepage
<img src="https://user-images.githubusercontent.com/50947930/142506123-f464cd2d-bfd1-4e8d-a167-c34ebc5c5c68.jpg" width="20%" height="20%">

**Comment by zend10** [comment]
Yeah, I noticed this. I've already made the change for v.2.0.

**Comment by N0D4N** [comment]
Thanks for answer, closing this.
