### ISSUE TITLE
Bio not working

### ISSUE THREAD

**Issue by BuriBuriZymon** [zend10/AL-chan#84]
Fire some reason I'm unable to see my bio.
It only displays small box with obj written in it

**Comment by zend10** [comment]
It's most likely because it fails to load the image? Would you share me your username so that I can check it out?

**Comment by BuriBuriZymon** [comment]
Ty for replying.

My username is Luffyoniisan

**Comment by zend10** [comment]
I have not got a report about giphy, but for some reason the library I use can't load from catbox.

**Comment by BuriBuriZymon** [comment]
So should i change the website i used?
Can you recommend me which website i should be using for uploading the
photos?

**Comment by zend10** [comment]
I personally create my own private server in Discord and upload my images there.

Maybe if someone else has a other solution, please do tell.

**Comment by BuriBuriZymon** [comment]
Idk really.
I guess discord is a better idea tho.
I'll try it thankyou.

**Comment by BuriBuriZymon** [comment]
I'm sorry to disturb you again bro
but
it's still not working.
I used discord this time.

**Comment by zend10** [comment]
Alright I've rechecked your input. Can you try using the markdown below? The problem is previously there's a space between the parentheses and the url `image1000( https://.....)`. I know it works on the web but I can't process it as flexibly in the app. I also change your `img1000` to `img100%` because 1000 is a fixed width and won't look good in the app.

```
img100%(https://media.discordapp.net/attachments/917415478035632171/917417028015521802/fc37a663-26b7-4c9e-9f9d-0aebfc17c947.gif)
img100%(https://media.discordapp.net/attachments/917415478035632171/917416224265220106/project_20211206_1932523-01.png)
img100%(https://media.discordapp.net/attachments/917415478035632171/917416223757725756/project_20211205_1113599-02.png)
```

**Comment by BuriBuriZymon** [comment]
Okay bro.
Let me try.
Thankyou tho.

**Comment by BuriBuriZymon** [comment]
It ain't working bro😔

**Comment by zend10** [comment]
Really? I can already see it in your profile.

**Comment by BuriBuriZymon** [comment]
It worked.
Sorry.
And thankyou.
Can you share your AL username with me?

**Comment by BuriBuriZymon** [comment]
And bro i don't really understand these things so i was wondering if i can
link my profile in that png in my  bio where I've wrote my profile name.

**Comment by zend10** [comment]
Yes, sure you can put a link into an image. Though it's not being handled well in the app. You can see more about it here https://anilist.co/forum/thread/6125.

**Comment by BuriBuriZymon** [comment]
Thankyou
