### ISSUE TITLE
Consider adding this app to F-Droid

### ISSUE THREAD

**Issue by X9DF** [zend10/AL-chan#86]
[F-Droid](https://f-droid.org/) is an alternative to the Play Store consisting of a catalogue of FOSS apps.

The niche of anime tracking apps outside the Play Store is mostly non existant, and I have no knowledge of any app in F-Droid which provides a client for Anilist.

F-Droid works with a system of repositories that serve lists of information about apps and updates. I'd recommend trying to get into @IzzySoft's repository, as its quite popular and the standards are lower than those of the official one (see [here](https://gitlab.com/IzzyOnDroid/repo/#what-are-the-requirements-an-app-must-meet-to-be-included-with-the-repo) for those and the repository to open an issue to get the app included).

Serving the app on F-Droid would however add some maintainance:
- F-Droid focuses on privacy, which means that telemetry is usually a no-go there. Currently it seems the app breaks when it's blocked (Getting a toast with "403", logcat complains about firebase being blocked with not much more that is relevant. Could also be due to a lack of google play services on my device).*

*This should be less of an issue with Izzy's repo.

- Releases would need to be served to both the Play Store and a Githuv/Gitlab/Etc repository.

**Comment by onkoe** [comment]
According to #73, this is a goal for V2
