### ISSUE TITLE
Adding New Entries

### ISSUE THREAD

**Issue by ImPudding-tech** [zend10/AL-chan#9]
Do you Have A plan Having New Entries submission in Al CHAN? 

![Screenshot_20200727_175131_com.android.chrome.jpg](https://user-images.githubusercontent.com/65703094/88529003-f7f19100-d031-11ea-910b-c388e6ddc7f1.jpg)

**Comment by zend10** [comment]
Unfortunately AniList doesn't provide the API for submission.

**Comment by zend10** [comment]
Not possible yet as of now since AniList doesn't provide the API.
