### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by hxpelessrxmantic** [zend10/AL-chan#91]
I deleted the app, reinstalled it and now I cannot log back in. When I click on the login screen, it does somehow login but then it glitches out and exits the app and this whole thing happens again when I open the app again. Please look into this since I love using the app.

**Comment by zend10** [comment]
Hmm? Try logging out from your browser as well. Then try logging in again.

**Comment by hxpelessrxmantic** [comment]
> Hmm? Try logging out from your browser as well. Then try logging in again.

Yes, I have tried this but it is the same thing.

**Comment by zend10** [comment]
I really can't figure out any other reason. There's no change regarding login flow since forever. 

Can you try this again to make sure: Logout from browser. Clear app data. Try login.

**Comment by hxpelessrxmantic** [comment]
> I really can't figure out any other reason. There's no change regarding login flow since forever.
> 
> Can you try this again to make sure: Logout from browser. Clear app data. Try login.

That's the thing. Even though I have logged out, it still somehow manages to login to my account without ever opening my browser for login authentication.

**Comment by zend10** [comment]
That's good to hear. I guess I'll be testing login flow on multiple browsers.
