### ISSUE TITLE
Rate limit issue

### ISSUE THREAD

**Issue by therealsbeve** [zend10/AL-chan#93]
The app is very problematic to use at the moment as clicking around just a bit will cause it to go blank and get the rate limit message. Any fix bring made for this?

**Comment by peepincreepin** [comment]
Just chiming in to say I get this all the time too. Even when I haven't had the app open (and haven't had any notifications) for a few days, I'll open the app and immediately get a message about hitting the rate limit.

**Comment by therealsbeve** [comment]
> Just chiming in to say I get this all the time too. Even when I haven't had the app open (and haven't had any notifications) for a few days, I'll open the app and immediately get a message about hitting the rate limit.

Yeah its gotten worse as time has gone by. Just clicking on any tab once triggers the rate limit message and stopping further interactions with the app.

**Comment by kal5331** [comment]
I wonder if it's something to do with server/API limits. The question is if it's the database connected to the app, or an external API limiting the requests based on the application token.

**Comment by kl5331** [comment]
I wonder if it's something to do with server/API limits. The question is if it's the database connected to the app, or an external API limiting the requests based on the application token.

**Comment by therealsbeve** [comment]
Yeah im not sure either, but it's gotten so much worse as of late. All it takes is one or two pages and it just stops loading and only resumes after 1 to 2 minutes.

**Comment by kl5331** [comment]
Same here. If it's an external API limiting effect, then it should resolve with time and may be just during high traffic times, otherwise, the database thats being used could have read limits to limit costs

**Comment by therealsbeve** [comment]
Yeah I think the problem doesn't necessarily lie with this app itself, just Anilist as a whole. I was using this app and got the rate limit issue and so I switched to a different Anilist client "Anilib" and nothing was loading on it either.

**Comment by kl5331** [comment]
You could be right and just less people using anilib. As anime become more popular, I wonder if Anilist is going to start ads, if they havent already. Server costs and such can be expensive, but for now, guess I'll be updating my lists during non-peak hours

**Comment by therealsbeve** [comment]
What time is non-peak hours for yourself? I'm trying to adjust when I use the app as well to see if it makes any changes.

**Comment by kl5331** [comment]
Probably about 4 hours from now in the EST

**Comment by peepincreepin** [comment]
The anilist documentation page says their rate limit is 90 requests per minute. https://anilist.gitbook.io/anilist-apiv2-docs/overview/rate-limiting

I'm admittedly not super knowledgeable about this, but I feel like just using the app normally shouldn't be anywhere near close to hitting that limit? Unless they have changed their rate limit without updating the documentation?

**Comment by peepincreepin** [comment]
I also just tried anilib and oujo and they're working perfectly fine. So I don't think it's an issue with anilist; the problem seems to be with the al-chan app specifically.

**Comment by peepincreepin** [comment]
I think the issue is probably with the way that al-chan is using the API. I have tested with 2 other apps – anilib & oujo. I only ever get the rate limit from using al-chan. I load like three manga pages and instantly get rate limited for about a minute. If I try to use the other apps within this time period, they don't work.

> I was using this app and got the rate limit issue and so I switched to a different Anilist client "Anilib" and nothing was loading on it either.

This seems like the problem you had here. Anilist rate limits your entire account, so that's why you can't just switch to another app immediately; you have to wait a few minutes. 

However, if I don't use al-chan, but just use the other apps, I never get rate limited. They are a tiny bit slow, but I can continuously load pages with no issue.

So it seems the problem is being caused by al-chan.

**Comment by zend10** [comment]
I hope it's better now in the Beta app.
